 $Id: sample.msg,v 1.2 2001/04/10 00:27:27 hpa Exp $
Note that <Ctrl-P>...<Ctrl-W> can be used to delimit something
that is effectively a comment.
This message is displayed before the image.
syslogo.lss
This message is displayed after the image.

Please note colors do not work quite as expected in graphics mode!

04 RED 07 02 GREEN 07 01 BLUE 07
47 RED 07 27 GREEN 07 17 BLUE 07


